workspace = 1, defaultName:Masterthesis, on-created-empty: exec $terminal --workdir $HOME/Repos -e zsh -ic "source ~/.venv/h2/bin/activate; pa; sa; cd h2project; exec zsh"
workspace = 2, defaultName:Coding, on-created-empty: exec $terminal --workdir $HOME/Repos/h2project -e zsh -ic "source ~/.venv/h2/bin/activate; nvim bessy/phexphem.py; exec zsh", layout: master
workspace = 3, defaultName:LaTeX, on-created-empty: exec $terminal --workdir $HOME/Repos/Masterthesis -e zsh -ic "latexmk -pvc"
workspace = 4, defaultName:Writing, on-created-empty: exec $terminal --workdir $HOME/Repos/Masterthesis -e zsh -ic "nvim content; exec zsh"
workspace = 5, defaultName:Literature, on-created-empty: exec zotero
workspace = 6, defaultName:Communication, on-created-empty: exec bash -c "thunderbird & Telegram & signal-desktop & element-desktop"
workspace = 7, defaultName:Tinkering
workspace = 8, defaultName:Chill
workspace = 9, defaultName:Free-left
workspace = 10, defaultName:Free-right


