general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
}

listener {
    timeout = 300        # seconds of idle before locking
    # on-timeout = hyprlock
    on-timeout = if ! hyprctl activewindow -j | grep -q '"fullscreen":1'; then hyprlock; fi
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

