# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = konsole
$fileManager = dolphin
$menu = hyprlauncher
$browser = zen-browser


source = ~/.config/hypr/monitors.conf

source = ~/.config/hypr/autostart.conf

source = ~/.config/hypr/environment.conf

source = ~/.config/hypr/permissions.conf

source = ~/.config/hypr/look.conf

source = ~/.config/hypr/input.conf

source = ~/.config/hypr/keybinds.conf

source = ~/.config/hypr/workspaces.conf
