input-field {
    monitor =
    size = 200, 60
    outline_thickness = 0
    position = 0, -250
    halign = center
    valign = center
    # placeholder_text = <i>Password</i>
    placeholder_text = توكّل على الله
    font_family = Scheherazade New
    fade_on_empty = false
    outer_color = rgba(100, 55, 20, 1.0)
    inner_color = rgba(100, 55, 20, 0.2)
}

label {
    monitor = 
    # text = $USER
    text = السَّلام عليكَ أبا حمزة 
    text = cmd[update:60000] echo "$(h=$(date +%H); if [ $h -lt 9 ]; then echo صبّحك الله بالخير أبا حَمزة; elif [ $h -lt 18 ]; then echo السَّلام عليكَ أبا حَمزة ; else echo مساء الخير أبا حَمزة; fi)"
    font_family = Scheherazade New
    font_size = 40
    position = 0, 400
    halign = center
    valign = center
    color = rgba(100, 55, 20, 1.0)
}

# label {
    # monitor = 
    # text = توكّل على الله
    # font_family = Scheherazade New
    # font_size = 50
    # position = 0, -320
    # halign = center
    # valign = center
    # color = rgba(100, 55, 20, 1.0)
# }

background {
    monitor = 
    path = $HOME/Pictures/Wallpapers/no_dark_bg/basmalah_on_beige.jpg
    blur_passes = 2
    blur_size = 1
    brightness = 0.8
    vibrancy = 0.1
}


label {
  monitor =
  text = cmd[update:1000] date +"%A, %d. %B"
  color = rgba(100, 55, 20, 1.0)
  font_size = 22
  font_family = JetBrains Mono
  position = 0, 270
  halign = center
  valign = center
}

label {
  monitor = 
  text = cmd[update:1000] date +"%H:%M:%S"
  color = rgba(100, 55, 20, 1.0)
  font_size = 60
  font_family = JetBrains Mono Bold
  position = 0, 200
  halign = center
  valign = center
}
