workspace = 2, monitor:HDMI-A-1, on-created-empty: exec $terminal --workdir $HOME/Repos/h2project -e zsh -ic "source ~/.venv/h2/bin/activate; nvim bessy/phexphem.py; exec zsh"
workspace = 1, monitor:DVI-D-1, on-created-empty: exec $terminal --workdir $HOME/Repos/h2project -e zsh -ic "source ~/.venv/h2/bin/activate; exec zsh"




