workspace = 1, monitor:DVI-D-1, on-created-empty: exec $terminal --workdir $HOME/Repos -e zsh -ic "source ~/.venv/h2/bin/activate; pa; sa; cd h2project; exec zsh"
workspace = 2, monitor:HDMI-A-1, on-created-empty: exec $terminal --workdir $HOME/Repos/h2project -e zsh -ic "source ~/.venv/h2/bin/activate; nvim bessy/phexphem.py; exec zsh", layout: master
workspace = 3, monitor:DVI-D-1, on-created-empty: exec $terminal --workdir $HOME/Repos/Masterthesis -e zsh -ic "latexmk -pvc"
workspace = 4, monitor:HDMI-A-1, on-created-empty: exec $terminal --workdir $HOME/Repos/Masterthesis -e zsh -ic "nvim content; exec zsh"
workspace = 5, monitor:HDMI-A-1, on-created-empty: exec zotero
workspace = 6, monitor:HDMI-A-1, on-created-empty: exec bash -c "thunderbird & Telegram & signal-desktop" # TODO & element-desktop"




