wallpaper {
monitor = DVI-D-1
path = $HOME/Pictures/Wallpapers/mounted archer.jpg
}

wallpaper {
monitor = HDMI-A-1
# path = /home/abu-hamza/Sync/Hintergrundbilder/mihrab.jpg
path = ~/Bilder/Wallpapers/too-small/
fit_mode = contain
timeout = 4
}

splash = true
