wallpaper {
monitor = DVI-D-1
path = $HOME/Pictures/Wallpapers/
fit_mode = contain
timeout=53
}

wallpaper {
monitor = HDMI-A-1
# path = /home/abu-hamza/Sync/Hintergrundbilder/mihrab.jpg
path = $HOME/Pictures/Wallpapers/
fit_mode = contain
timeout = 61
}

splash = true
